### ISSUE TITLE
Style Helper

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#101]
@dcfreema @jelevoir https://bootstrapstudio.io/ help for bootstrapping your bootstrap web page :)

**Comment by jelevoir** [comment]
How deep can we go!?

**Comment by jelevoir** [comment]
As nifty as it is, I consider it the same as using Dreamweaver:
An unnecessary step if you know what you're doing. I feel like it would slow me down. =\

**Comment by jelevoir** [comment]
Fitting issue number, though. 
#101

**Comment by bpowell** [comment]
Haha, all good. I figured I'd show you guys this if you wanted to use it. I'll just close this issue then :)
