### ISSUE TITLE
Add all categories

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#119]
Add the categories to the create.sql file.

Wine, beer, liquor, garnish, soft drink

Any other categories we may need? I want to keep it simple?

**Comment by bpowell** [comment]
@pforgaciu @dcfreema @jelevoir @ehill2

**Comment by jelevoir** [comment]
I would say change soft drink to "Mixer" and you can cover all non-alcoholic additions (soda, juice, lime juice, bloody mary mixes) with one term.

**Comment by bpowell** [comment]
Would we want soft drink and mixer to be different? Just in case we have some pansy who just wants a (diet) coke?

**Comment by jelevoir** [comment]
I'm not sure. I definitely see your point though.
So where would you put club soda? You know, that nasty 'flavorless carbonated-water stuff' that is technically a soft drink but no one in their sane mind would ever order it on their own.

**Comment by bpowell** [comment]
Hmm good point. I'd probably put club soda as a mixer. Well we can talk about it at the meeting today, then update this ticket.

**Comment by bpowell** [comment]
Using all pop as 'Mixer'. Discussed at meeting.
