### ISSUE TITLE
Create Service and Model Classes

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#12]
To Do:
Create the following files.
edu/oakland/cse480/service/DrinkService.java,
edu/oakland/cse480/service/ItemService.java,
edu/oakland/cse480/service/DrinkOrder.java

**Comment by jelevoir** [comment]
Done:
Created the following files. 
edu/oakland/cse480/service/AbstractJdbcDriver.java,
edu/oakland/cse480/service/UserService.java,
edu/oakland/cse480/service/BusinessService.java,
edu/oakland/cse480/service/BarService.java,
edu/oakland/cse480/mvc/models/User.java,
edu/oakland/cse480/mvc/models/Business.java,
edu/oakland/cse480/mvc/models/Bar.java,
edu/oakland/cse480/mvc/models/Drink.java,
edu/oakland/cse480/mvc/models/Item.java,
edu/oakland/cse480/mvc/models/DrinkOrder.java

**Comment by bpowell** [comment]
Closing.
