### ISSUE TITLE
find a font-face

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#121]
To make our app more look a little better, I feel we need to find a font that can be used in the web app.

Unfortunately, we cannot use Coolvetica as a font-face due to the EULA saying it cannot be used on the web as an embedded font.

So we need to make sure whatever we use is:
- web-embed friendly
- in format woff, woff2, and ttf to provide maximum compatibility
- free!
- looks good with our logo font (even though I guess we could change that font)

**Comment by ehill2** [comment]
I have some ideas for this.  Trying to find one that meets those requirements and goes well with the logo. I'll show you guys when we meet.
