### ISSUE TITLE
Make DrinkQ logo clickable

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#122]
Should lead to the home page much like github

**Comment by bpowell** [comment]
Have it go to the main page. BTW we need a main page!

**Comment by ghost** [comment]
welcome.jsp

lol that should be a separate ticket

**Comment by ghost** [comment]
@jelevoir not sure this one if functioning correctly.  I merged the changes because I think this is a separate bug but when I click i simply get a "#" after the url

**Comment by jelevoir** [comment]
That is intended. 
In pull request #133, I stated that it will be hooked up to welcome.jsp once that page is designed. 
The link is technically clickable, it just doesn't go anywhere. ;]
