### ISSUE TITLE
Create a welcome page

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#137]
welcome.jsp is currently a very basic page that says "Hello [username if logged in]!"

This is the front page of our app.
Be creative, but don't make it too cluttered.

**Comment by ehill2** [comment]
`<jsp:directive.include file="/WEB-INF/jsp/header.jsp"/>
    <body>
        <div class="col-lg-12 mainContent">
            <h4 class="form-signin-heading"><a href="/cse480/register">New Users: Sign up now!</a></h4>

```
        <h4 class="form-signin-heading"><a href="/cse480/login">Existing Users: Sign in!</a></h4>

            </div>

 <div class="col-lg-12 mainContent">
    <h1 class="form-signin-heading">Welcome to drinkQ!</h1>
    <h4 class="form-signin-heading">DrinkQ is a new app that aims to make every bar experience the best one ever!</h4>
    <h4 class="form-signin-heading">Tired of showing up to bars with long lines, and not knowing when you will get a drink?</h4>
    <h4 class="form-signin-heading"><a href="/cse480/register">Sign up</a> to drinkQ today to have total control over your night out!</h4>

    </div>

<div class ="col-lg-12 third">
<h4 class="form-signin-heading">User profile page contains useful information and logs activity.</h4>
<img src="<c:url value="/img/profilemock.png" />"  />
</div>

<div class ="col-lg-12 third">
<h4 class="form-signin-heading">Easily view and search all of a bars available drinks with the drink list view.</h4>
<img src="<c:url value="/img/beerlistmock.png" />"  />
</div>

<div class ="col-lg-12 third">
<h4 class="form-signin-heading">Real time drink queue displayed in bar let's you know exactly when your order is ready.</h4>
<img src="<c:url value="/img/livequeuemock.png" />"  />
</div>


</body>
```

</html>`

![beerlistmock](https://cloud.githubusercontent.com/assets/16707668/13745751/28910504-e9c6-11e5-8553-2bb2bb56f4c3.png)
![profilemock](https://cloud.githubusercontent.com/assets/16707668/13745756/2dd6f370-e9c6-11e5-94c9-2f83fed214f8.png)
![livequeuemock](https://cloud.githubusercontent.com/assets/16707668/13745763/3089b1de-e9c6-11e5-859a-bf1e7b249098.png)

Here is the code for the welcome page I created.  It needs those three images as well, those are just mockups I made for now.  We can take actual screenshots of the pages they represent when they are finished.

**Comment by bpowell** [comment]
Closing, already completed in #155
