### ISSUE TITLE
Add proper error logging for SQL calls

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#144]
Add proper error logging of exceptions when calling SQL

**Comment by bpowell** [comment]
@jelevoir did you want to take over this one? All you need to do is in the catch block add a:
log.error("", e);

That way if we run into any SQL errors, we can see what they are.

**Comment by jelevoir** [comment]
I can definitely do that.
I actually did this for a service method when trying to troubleshoot. =]

**Comment by bpowell** [comment]
Haha awesome, thanks! Yeah I kept forgetting to add them when I was having trouble
