### ISSUE TITLE
Define standard for code

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#146]
Tabs or spaces? etc

@jelevoir @dcfreema what do you guys think? Right now our code seems to be a mixture, we should fix that.

**Comment by jelevoir** [comment]
Spaces.
I used to be a big proponent for tabs, but have since migrated away from them.

**Comment by jelevoir** [comment]
Actually, I may have used tabs in a few files out of habit. I had been using tabs up until right before this semester.

**Comment by bpowell** [comment]
4 spaces for indent work for you? Or more/less? I prefer 4 for java, but if you want to do something different let me know.

**Comment by jelevoir** [comment]
4 is what I'm familiar with.

**Comment by ghost** [comment]
I have been using tab with set tabstop=2.
I can change though I really prefer hitting tab once instead of space two or four times...

**Comment by jelevoir** [comment]
We have decided on using 4 spaces for indentation. 
How you use your editor to accomplish this is up to you. =]
Closing!
