### ISSUE TITLE
ownercontroller updatehours needs new success message

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#166]
Currently when the hours are updated, it shows sunday's hours in the success message. xD
Make it say "Hours Updated!" or something.

**Comment by bpowell** [comment]
My bad...

**Comment by jelevoir** [comment]
I thought it was hilarious. It was just so unexpected I thought it may have been intentional. =]

**Comment by bpowell** [comment]
Haha, let's go with that.
