### ISSUE TITLE
Home page can scroll off to the right

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#184]
![issue](https://cloud.githubusercontent.com/assets/7514723/14061696/dc61481a-f35c-11e5-85ef-52d8bc008dfc.png)

**Comment by jelevoir** [comment]
I'm not getting this. What browser are you using and what branch?

**Comment by ghost** [comment]
I am on master, up to date current.  Last commit: f46e2da

Google chrome. Resolution: 1366x768

**Comment by ghost** [comment]
#187
