### ISSUE TITLE
Java Date issue

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#197]
ERROR [main] 2016-03-29 09:02:14,699 - 
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select \* from drinkorder]; nested exception is java.sql.SQLSyntaxErrorException: incompatible data type in conversion: from SQL type TIMESTAMP WITH TIME ZONE to java.lang.Integer, value: instance of org.hsqldb.types.TimestampData

**Comment by bpowell** [comment]
Closing ticket. Not a problem, we are removing that service.
