### ISSUE TITLE
Add Mini-bar stats to Display

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#226]
@bpowell

**Comment by bpowell** [comment]
@jelevoir 
I was thinking for stats, something like:
Total number of available drinks
Total number of drinks served
Total number of drinks in the queue

If that works for everyone I will make a new issue for each of those and add them in so this can be done.

**Comment by jelevoir** [comment]
That works for me. If you want to just leave them all under this issue, I'll most likely just be throwing them all in a single branch anyway.
I'm finishing up #225 tonight.
Tomorrow I'll be doing this in the morning. I took tomorrow off to work on stuff.

**Comment by bpowell** [comment]
One more we need to add is total wait time for the queue.

I will add those to this branch so you can use them. Good idea taking today off.  See you tonight!
