### ISSUE TITLE
Add border around bars in barList

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#238]
THis will make the new style pop

**Comment by ghost** [comment]
After #232 is merged

**Comment by jelevoir** [comment]
Hold off on this. I'm restructuring the barview page so this may not be necessary.

**Comment by ghost** [comment]
@jelevoir with your sidebar do you still think this is necessary?

**Comment by jelevoir** [comment]
Probably not. 
If you wanna mess around and throw up a screenshot, feel free. But I think the idea would have worked best with the previous layout.
