### ISSUE TITLE
Add images to text at the bottom of display.jsp

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#239]
Need to find a set of icons

**Comment by jelevoir** [comment]
Are you talking about generic drink icons?
If so, I merged some in that I created late February.
[/img/drink_icon/*.png](https://github.com/bpowell/cse480/tree/master/webapp/src/main/webapp/img/drink_icon/)

**Comment by ghost** [comment]
No something like a notification icon to go above the content that says "notifies you when drink is complete"

**Comment by jelevoir** [comment]
I don't get it. =[
I'll probably just have to see it to understand.

**Comment by ghost** [comment]
I will send u screen shots!

**Comment by ghost** [comment]
@bpowell what do you think about these? Simple but larger than glyphicons http://www.flaticon.com/packs/web-navigation-line-craft

**Comment by bpowell** [comment]
Those should work fine.

**Comment by jelevoir** [comment]
We'll have to place a link with 'designed by Freepik' somewhere visible on our site according to the license.
Where would you want that to go?
Also, I'm still a bit confused about how these would be used. o.0

**Comment by ghost** [comment]
@jelevoir we could hide that at the bottom, small text.
These would help break up the monotony on the landing page.  Ww could have an icon for each chunk of text.

**Comment by jelevoir** [comment]
Merged into master.
