### ISSUE TITLE
Drink model errors

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#28]
[ERROR] /Users/brandon/p/cse480-env/cse480/webapp/src/main/java/edu/oakland/cse480/service/DrinkService.java:[82,14] cannot find symbol
  symbol:   method setId(int)
  location: variable d of type edu.oakland.cse480.mvc.models.Drink
[ERROR] /Users/brandon/p/cse480-env/cse480/webapp/src/main/java/edu/oakland/cse480/service/DrinkService.java:[86,14] method setIconUrl in class edu.oakland.cse480.mvc.models.Drink cannot be applied to given types;
  required: no arguments
  found: java.lang.String
  reason: actual and formal argument lists differ in length

**Comment by jelevoir** [comment]
Brandon created branch CS-28, it was merged into master. Thus resolving this issue.
