### ISSUE TITLE
Create user/roles tables

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#3]
Create the database tables for users and roles. This is what will control the access to the application.

**Comment by jelevoir** [comment]
I'm currently working on this. First draft of entire database will be completed by Sunday night.

I'm working with the idea of 8 tables:
User
Group
Location
Bar
Queue
Drink
Item
Order

I created a rough sketch for each view as well. It helped me visualize the database.
I'll upload those, but know that they aren't finalized by any means. We need to all get together and talk about the features and screens/views the app will have. It will help solidify what the final database layout looks like.

If you have any comments or feel I'm missing something, please reply.

**Comment by jelevoir** [comment]
I have completed what I feel is a great starting point for database structure. I will be pushing an updated create.sql file to the CS-1 branch tomorrow as I am busy the rest of the night.

**Comment by bpowell** [comment]
Okay, cool. I'll wait and take a look at what you got.
