### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#34]
Create site logo. @dcfreema @ehill2 if you guys want to work together or make a few designs then hash them out that would be awesome. Get maybe a few designs then we can put it up to a vote. 

If anyone else wants to take a crack at it go a head. We should try and get this done before next week so we can start making our pages.

**Comment by jelevoir** [comment]
![drinkq_logo_sm_glass_transparent](https://cloud.githubusercontent.com/assets/13627221/13028194/a3065382-d235-11e5-8576-aa2953bffdc7.png)
![q_icon_w_glass_transparent](https://cloud.githubusercontent.com/assets/13627221/13028195/a9aa233a-d235-11e5-8597-7765d97f543c.png)

**Comment by bpowell** [comment]
@jelevoir those look perfecto! Commit those to a branch under the folder: src/main/webapp/img/

**Comment by jelevoir** [comment]
@bpowell @dcfreema
Do you think it's necessary to create an SVG for the logo? 
If PNG is okay, what resolution should I scale the logo to? 
(I'm assuming the icon should be 512x512 as that is the resolution android displays in the Play Store)
