### ISSUE TITLE
create bartender view of display.jsp

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#38]

**Comment by ghost** [comment]
@bpowell I think I made a mistake, this will be a variation of display.jsp right?
Please correct me or close.

**Comment by bpowell** [comment]
It will be similar to display.jsp but will have extra functions. I'm not sure yet on how we will handle the differences. Leave this open for now.

**Comment by bpowell** [comment]
We will have to integrate #91 to this as well. The page can be created, but extra checks will have to be added to make sure a bartender from one bar cannot modify another bars queue.

**Comment by ghost** [comment]
@bpowell I will start by using display as a template then consult you for further details, sound good?

**Comment by bpowell** [comment]
Works for me!

**Comment by ghost** [comment]
@jelevoir how are we going to handle this now? Is this issue outdated?

**Comment by jelevoir** [comment]
We can use security tags to create conditionals for if a bartender is on the page.
I'll reassign it to myself.

**Comment by bpowell** [comment]
@jelevoir how is this going?

**Comment by jelevoir** [comment]
I was planning on working on this today. I don't think this will take very much time.
The hardest part will be implementing the closing of a drink.

**Comment by bpowell** [comment]
If you want help with the closing of a drink let me know, I can do that part I think pretty easy. I was thinking of hitting an API that would handle notifying the user that the drink was completed and updating the database.

**Comment by jelevoir** [comment]
Branch merged with master.
Creating new issue about sending email notification when drink is closed.
