### ISSUE TITLE
Update BusinessService.java

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#43]
This class needs additional methods:
- getBusinessById()
- getBusinessByName()
- updateBusinessById()
- insertBusiness()
- deleteBusinessById()

**Comment by bpowell** [comment]
Sorry to burst your bubble on this, but I have fixed Business #46 and Bar #45  services up already :(.  Checkout issue #35 with branch CS-35 f89d34a230d66a9194cd76994031da377dddfe19

**Comment by bpowell** [comment]
I can merge what you have added that I might have missed into what I have been working on. It looks like you have a few extra database things I forgot.

**Comment by bpowell** [comment]
I probably should have named that issue something a little better so you didn't tackle it as well. Sorry about that.

**Comment by jelevoir** [comment]
No worries. I didn't spend too much time on them. Most of the time I spent on them involved fixing the commits I added an incorrect message to. =X
I'll leave it to you if you can take anything from those branches. I'm going to remove the pull requests, but leave the branches. Delete them when you have all you need from them.
