### ISSUE TITLE
Add 403 handling.

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#74]
If users are not admin level, when trying to access page they are given 404 page and not 403 error.

Need to do:
- Add 403 page.
- Make access denied work?

**Comment by jelevoir** [comment]
Hey @bpowell,

Is this worth looking into? 

Since technically the /admin/\* resources aren't going to be available to non admin users, is it okay that it is returning a 404?

According to an [RFC by the IETF](http://tools.ietf.org/html/rfc2616#section-10.4.4), it seems like throwing a 404 (the current way it is, if we merge #73) is the way to go.

**Comment by bpowell** [comment]
That's fine if it does a 404. Just as long as they can't view anything they shouldn't :)

**Comment by jelevoir** [comment]
We've decided to 86 the issue. HAHAHAHAHA
