### ISSUE TITLE
Create ERD for database

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#8]
We need an ERD for the database we have. This will be a living document. As we change the database this ERD will have to be updated

**Comment by jelevoir** [comment]
Paul created an initial diagram February 11th, 2016.
https://drive.google.com/open?id=0B99OkORpaSJZRDdtalBjQi1nNEU

**Comment by jelevoir** [comment]
I made a couple revisions February 13, 2016.
https://drive.google.com/open?id=0B7F36TM_wazlbzBzcmJobTBPWDQ
