### ISSUE TITLE
change links to absolute paths instead of relative

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#87]
For example, going to http://[site]:8080/cse480/admin/ as a normal user will display 404 page. 
There is a link at the bottom of the page:
`<a href="barview">Return to Bars!</a>`
This is supposed to return you to barview.jsp. 
It works for any http://[site]:8080/cse480/\* page but not http://[site]:8080/cse480/_/_ page.

To fix:
Change it to be an absolute path, not relative path.

This is a wider spread issue than just the /admin/ page. Look at them all.

**Comment by bpowell** [comment]
use <c:url...> for generating the absolute path for the urls. Example: https://github.com/bpowell/cse480/blob/master/webapp/src/main/webapp/WEB-INF/jsp/changepassword.jsp#L5

**Comment by ghost** [comment]
@jelevoir when you complete this help me out for a few minutes so i can do issue #79 in the same fashion.

**Comment by ghost** [comment]
#95
