### ISSUE TITLE
create functional profile page

### ISSUE THREAD

**Issue by jelevoir** [bpowell/cse480#94]
Show recent information such as:
- Previous 5 drinks ordered.
- Link to update account information.

@bpowell , @dcfreema , @pforgaciu , @ehill2 :
Any other ideas for what should be on the profile page?

**Comment by bpowell** [comment]
Link to change password is I think the only thing they should be able to edit for themselves. I don't want to deal with changing email addresses and the likes.

Maybe add previous bars visited?

**Comment by jelevoir** [comment]
Branch CS-94 update with the following:
- Previous 5 drinks has been added.
- Change password link has been added.

Will be adding previous 5 bars tomorrow.
Update Username: field to show username instead of email.
